server: # 服务端口号【配置】
   port: 8000
   
spring: # JPA Hibernate【配置】
   jpa: 
      generate-dll: false
      show-sql: true
      hebernate: 
         ddl-auto: none
   datasource: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://locahost:3306/test
      username: root
      password: 123456
   application: 
      name: jzgk-boot
      
eureka: # 注册中心【配置】
   client: 
      serviceUrl: 
         defaultZone: http://localhost:8761/eureka/
   instance: 
      prefer-ip-address: true 
      
logging: # 日志【配置】
   level: 
      root: INFO
      org.hibernate: info
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
      
info: # info【配置】
  app:
    name: "DayOne"
    description: "Parent pom providing dependency and plugin management for applications
		built with Maven"
    version: "0.0.1-SNAPSHOT"
    encoding: "UTF-8"
    java:
      version: "1.8.0_191"
